theme: jekyll-theme-cayman
title: „ÅäÂÆ¢Êßò„ÄÅ„Çà„ÅÜ„Åì„ÅùÔºÅ
description: „Åì„Åì„ÅØ„ÄÅÁßÅ„Åå„Ç¥„ÉüÊç®„Å¶Â†¥„ÇíÊâã„ÇíÂÖ•„Çå„Å¶ÈÅä„Å≥Â†¥„Å´„Åó„ÅüÂ†¥ÊâÄ„Åß„Åô„ÄÇ‰ºö„Åà„Å¶„ÅÜ„Çå„Åó„ÅÑ„Çà (,,>Ôπè<,,)
show_downloads: false
hide_github: true

buttons:
  - text: "üê±"
    href: "https://github.com/chiyuukei/blog/"
